### ISSUE TITLE
map[btcutil.Address]btcutil.Amount in sendmany is a pretty dangerous

### ISSUE THREAD

**Issue by glenherb** [btcsuite/btcrpcclient#112]
For example take this code:

```
amounts := make(map[btcutil.Address]btcutil.Amount)
for _, p := range paymentsToMake {

  addr, _ := btcutil.DecodeAddress(p.Address, net)
  amounts[addr] = amounts[addr] + p.amount
}
client.SendMany("", amounts)
```

There is a subtle problem that looking up in amounts will never work, because despite btcutil.Address being comparable, it's not a logic comparison. When it's finally sent over rpc, one of the payments can be silently be dropped

**Comment by jrick** [comment]
Yeah, this is an issue because we set the pointers to the concrete address type as the Address interface value.  If we put the non-pointer type in the interface I believe it will equate correct, since it will compare the actual struct values themselves instead of doing pointer equality.

**Comment by jrick** [comment]
Sadly that's not possible since we are using pointer receivers, so the values themselves cannot satisfy the interface: https://play.golang.org/p/J7UWiO7x_o

(change the pointer receiver to a non-pointer and notice how the commented out code now compiles, and evaluates to true.)

**Comment by jrick** [comment]
We are still stuck with this data structure though since it has to encode to a json object for the bitcoin json-rpc api.  In my mind it makes more sense to provide an (ordered) array of address+value objects to add as outputs for the transaction, but this would be incompatible with the existing api.

**Comment by FrozenPrincess** [comment]
This seems like a pretty simple fix, no?

The function is currently:

```
func (c *Client) SendManyAsync(fromAccount string, amounts map[btcutil.Address]btcutil.Amount) FutureSendManyResult {
	convertedAmounts := make(map[string]float64, len(amounts))
	for addr, amount := range amounts {
		convertedAmounts[addr.EncodeAddress()] = amount.ToBTC()
	}
	cmd := btcjson.NewSendManyCmd(fromAccount, convertedAmounts, nil, nil)
	return c.sendCmd(cmd)
}
```

and just needs to be changed to:

```
func (c *Client) SendManyAsync(fromAccount string, amounts map[btcutil.Address]btcutil.Amount) FutureSendManyResult {
	convertedAmounts := make(map[string]float64, len(amounts))
	for addr, amount := range amounts {
                encodedAddress := addr.EncodeAddress()
		convertedAmounts[encodedAddress] = convertedAmounts[encodedAddress] + amount.ToBTC()
	}
	cmd := btcjson.NewSendManyCmd(fromAccount, convertedAmounts, nil, nil)
	return c.sendCmd(cmd)
}
```

**Comment by jrick** [comment]
I'm not happy with that either because two outputs both paying to the same address is not the same thing as a single payment of the combined amount.

While the API here is pretty stupid, this is actually not *technically* a problem with the fact that bitcoin uses a JSON object keyed by addresses for representing these, as JSON does allow (but discourages) duplicate keys.  It becomes a problem for us (and implementations in many other languages) that use a hashmap/btreemap/etc. for representation of the object.

I also think the original issue was talking more about the general fact that map[btcutil.Address]foo is generally a bad idea, or that you must be very careful using them.  But then again, it's no more dangerous than comparing btcutil.Address objects already, since that will also just do a memory address comparison.

**Comment by FrozenPrincess** [comment]
> While the API here is pretty stupid, this is actually not technically a problem with the fact that bitcoin uses a JSON object keyed by addresses for representing these, as JSON does allow (but discourages) duplicate keys. 

Well, it's technically a problem in the sense it's currently not working. I just tested (against bitcoin core) with a `map[btcutil.Address]btcutil.Amount` with two same-but-different addresses. When it sent a transaction, one of the entries overwrote the other. 

I didn't debug the network traffic, so I'm not sure if the problem is in the json or in bitcoin core. However, there is an actual problem

**Comment by davecgh** [comment]
This issue was moved to btcsuite/btcd#999
