### ISSUE TITLE
OP_RETURN Transaction

### ISSUE THREAD

**Issue by GaetanCathelain** [btcsuite/btcrpcclient#123]
Hi,

Lately I've been trying to use btcrpcclient and the btcsuite to make transactions with an OP_RETURN script. It seems impossible to implement with the provided CreateRawTransaction if I'm correct, so I wanted to ask if there is any way to implement this ?

Thanks :) 

Edit: I'm using Bitcoin core (bitcoind) on the testnet chain

**Comment by davecgh** [comment]
This lib is fairly outdated as compared to Bitcoin Core at this point.  The `createrawtransaction` RPC at the time it was implemented only had the ability to specify addresses (as opposed to the newer addition of `data` which is required to create an `OP_RETURN` transaction).  Consequently, you won't be able to use the `CreateRawTransaction` to create such a transaction directly.

Basically, you have 2 choices:

1) Just create the transaction yourself using the `github.com/btcsuite/btcd/wire` and `github.com/btcsuite/btcd/txscript` packages, which is also much more efficient since you don't have to make a network call.
2) Make use of `btcrpcclient.RawRequest` which will allow you to manually form the `createrawtransaction` request to include the options available in later version of Core that aren't in this lib.

**Comment by GaetanCathelain** [comment]
Alright thank you for your reply, it's exactly what I was looking for.

Good luck for this awesome project !
