### ISSUE TITLE
Async channel results are useless for select operations

### ISSUE THREAD

**Issue by jrick** [btcsuite/btcrpcclient#72]
I have code that needs to do something like:

```
var asyncResult btcrpcclient.FutureFooResult
for {
    select {
    case <-beginAsyncRequest:
        asyncResult = client.FooAsync()
    case result := <-asyncResult:
        // Use the result
    }
}
```

This can't be done since the result returned by each *Async function is a channel of the unexported btcrpcclient result type.  More specifically, while receiving on the channel works, the result is unusable.

The FutureFooResult.Receive function is not an option here as it can not be used in a select statement.

As long as only the error is needed, and not the RPC result (which is saved as a byte slice), this quick and dirty hack works:

```
func (r *result) Err() error {
    return r.err
}
```

This has its own downsides as well since it declares an exported function with an unexported receiver type (essentially, this would be undocumented by godoc).  There is also no equivalent function that could be added for the result since it would leave the result JSON marshalled.

Without being able to specify a generic result type (grmbl), I don't see any good way to solve this problem for every case.

**Comment by jrick** [comment]
Another workaround could be to spawn a new goroutine that blocks on Receive, and then sends a type that I define (either just an error, or both the result and error in a struct) to a channel received by the select.  I feel awful for having to do this though.

**Comment by davecgh** [comment]
While I understand where you're coming from, I don't think there is much to be don here.

The problem is returning a channel would end up needing interfaces and lead to caller type assertions.  Also, it would end up need a bunch of types to encapsulate the error akin to the following:

```Go
type GetBlockResult struct {
	Block *wire.MsgBlock
	Err error
}
```

Then, the package itself would end up having to launch goroutines for all of those anyways.

I believe the right answer is what you suggest in your second comment where the caller can launch the goroutine if it desires.
