### ISSUE TITLE
Getting block by hash doesn't return height

### ISSUE THREAD

**Issue by soggie** [btcsuite/btcrpcclient#86]
`GetBlock` takes a hash and returns a raw block, but that doesn't come with height. So this means if I want to get a raw block along with its height, I have to:

1. Use `GetBlockVerbose` to get a verbose block
2. Use `GetBlock` to get a raw block
3. Use `SetHeight()` to set the height from the verbose block to the raw block

Is this a bug? I haven't dug into the code yet.

**Comment by jrick** [comment]
It's more of an oversight in the RPC API than this client's API, since there is simply no way to query for both the raw block and its height together.

That said the `GetBlock` API we expose from the client should probably be returning a `*wire.MsgBlock` instead of `*btcutil.Block`, since the non-verbose getblock is just returning a raw block.

**Comment by davecgh** [comment]
I've made the recommended change to return a `*wire.MsgBlock` in PR #93.
